[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]

# Route all requests to the serverless function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true
