[build]
  command = "npm install"
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index:handler"
  status = 200
